# Generated by Django 2.2.6 on 2020-01-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
